### ISSUE TITLE
Changing the Core slider for an ROTank causes the tank to visibly change length

### ISSUE THREAD

**Issue by ajvaughan** [KSP-RO/ROLibrary#15]
Steel modular ROTank.  Changing the Core slider between 1.0x Kerolox and 0.25x Kerolox cause the tank to visibly change length.  Note that the fuel mass doesn't change, and the length slider doesn't change.  If I nudge the length slider slightly the tank resizes back to the correct length. There are other possibly related issues detailed below.

Discord discussion starts at https://discord.com/channels/319857228905447436/620690446540341261/988130866989531187

Images.
Starting with the core set to 8.0x-Kerolox
![screenshot2](https://user-images.githubusercontent.com/4538295/175048516-cc13bdb3-2db4-4faa-ab1b-43c01942e73d.png)

Cycling to the next Core (1.0x-Kerolox) option with via the RH ">>" button.  Note how the tank reinforcement looks too long.   
![screenshot3](https://user-images.githubusercontent.com/4538295/175050498-b0131a58-27df-4400-ab0a-1c4da8718ff9.png)

Cycling to the next Core option (0.25x-Kerolox).  Note the visual change in length, without a change in Mass or dV, how the texture changes and that the CoreTex slider disappears from the PAW.  

![screenshot4](https://user-images.githubusercontent.com/4538295/175051364-6f000427-1358-4b3d-8f7e-de2c4a0a14ef.png)
If I nudge the length slider slightly (eg 11.61m) the visual length is now correct.

Thanks for all your work on RO/RP-1.

**Comment by pap1723** [comment]
I bet I know the issue here...

There is a minimum value (how small something can be scaled vertically) and a maximum value (how large something can be scaled vertically). Changing the core parts was never intended to originally be used the way I have implemented them. They were originally going to be parts that set the length by changing the model and then using VScale to get a little more stretch.

If you have something that is like 8 to 1 in terms of length to diameter ratio, the tank model is only allowed to stretch so much visually. I think there is an easy fix to this by setting the VScale on the core tanks to like 0.1 and 50. I'll test it out and push a fix if it works.

**Comment by pap1723** [comment]
This was fixed in ROTanks by changing the min/max vScale.
